l# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      note:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Message to write into site log'
        # Default value if no value is explicitly provided
        default: 'Site update'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Write update note to file
    run: |
      echo "Update on $(date): ${{ inputs.note }}" >> site-log.txt

  - name: Commit changes
    run: |
      git config --global user.name "github-actions"
      git config --global user.email "github-actions@github.com"
      git add site-log.txt
      git commit -m "Automated site note update"
      git push
